### ISSUE TITLE
NKU Online Judge 存在任意用户密码重置漏洞

### ISSUE THREAD

**Issue by lazy-forever** [ArcanusNEO/ArcOJ-BackEnd#94]
## 漏洞复现

重置密码界面抓包

<img width="520" alt="重置密码" src="https://github.com/user-attachments/assets/9e5d1db7-ff64-453b-89fa-7e00f5124b7f">

修改发送验证码邮箱为已知邮箱，非南开邮箱也可以，拿到Cookie ec字段值

<img width="1004" alt="屏幕截图 2024-10-25 140437" src="https://github.com/user-attachments/assets/4e46b2c9-95ea-41f4-a792-d075aa2a1489">

从已知邮箱处拿到验证码

<img width="203" alt="cha" src="https://github.com/user-attachments/assets/64761351-4b26-40b3-826b-79f029386eea">

填入验证码界面，再次抓包

<img width="561" alt="重置2" src="https://github.com/user-attachments/assets/455a8d8f-d283-4dc0-bc78-590b3c61bf94">

将Cookie ec字段修改为之前拿到的ec字段

<img width="1003" alt="屏幕截图 2024-10-25 140731" src="https://github.com/user-attachments/assets/140c6fea-ed18-4a77-909c-9d9ac45cf537">

成功重置任意用户密码

## 漏洞点

在`routes/email-captcha.mjs`处生成验证码给邮箱，返回 md5(captcha + salt) 的jwt签名，其中jwt信息中未对邮箱加约束

![image](https://github.com/user-attachments/assets/6a766412-4500-4d81-960d-01b0b9bc898e)

在`routes/reset.mjs`处验证传入Cookie ec字段jwt，取md5值并验证与 md5(传入的captcha + salt) 是否相等，未对邮箱信息进行验证

![image](https://github.com/user-attachments/assets/d368daa7-f0f5-4ee2-acea-b9578a44f32e)

另外，总感觉salt字段又作为jwt hs256的密钥，又作为重置密码的盐值，看起来很不安全的样子🫠

**Comment by zzzhj514** [comment]
Hacked BY hbw

**Comment by ArcanusNEO** [comment]
非常感谢🙏，这个bug有已被利用的迹象吗

**Comment by lazy-forever** [comment]
> 非常感谢🙏，这个bug有已被利用的迹象吗

暂时没听说，除了我拿来测试（

**Comment by ArcanusNEO** [comment]
打了个补丁，应该修复了；学校的维护人有联系过吗？

**Comment by lazy-forever** [comment]
> 打了个补丁，应该修复了；学校的维护人有联系过吗？

没，不知道维护人是谁

**Comment by ArcanusNEO** [comment]
> > 打了个补丁，应该修复了；学校的维护人有联系过吗？
> 
> 没，不知道维护人是谁

我和他@Siannochan说了，应该这两天会部署上新代码

**Comment by lazy-forever** [comment]
刚刚想了一下，这么修复感觉还是会有问题

- email-captcha接口传入 学号@mail.nankai.edu.cn.xxx.com xxx.com为自己的域名邮箱
- 从自己的域名邮箱拿到验证码
- reset/password接口传入 学号@mail.nankai.edu.cn   emailCaptcha传入.xxx.com+验证码，还是可以绕过

另外，md5函数的这种写法很容易受到 hash长度扩展攻击 ，推荐使用更安全的密码算法

**Comment by ArcanusNEO** [comment]
> 刚刚想了一下，这么修复感觉还是会有问题
> 
>     * email-captcha接口传入 学号@mail.nankai.edu.cn.xxx.com xxx.com为自己的域名邮箱
> 
>     * 从自己的域名邮箱拿到验证码
> 
>     * reset/password接口传入 学号@mail.nankai.edu.cn   emailCaptcha传入.xxx.com+验证码，还是可以绕过
> 
> 
> 另外，md5函数的这种写法很容易受到 hash长度扩展攻击 ，推荐使用更安全的密码算法

对验证码再 hash 了一次，不知道这种做法是不是密码学上的最佳实践。

这里的 hash 方法改成了 blake2，但是落库的密码因为历史原因还是保留 md5，要改的话所有人都必须重置密码，代价有点大。

虽然 md5 已经不安全了，不过我想了解一下对这个oj来说可以用合理的代价达成一次攻击吗？

**Comment by lazy-forever** [comment]
> > 刚刚想了一下，这么修复感觉还是会有问题
> > ```
> > * email-captcha接口传入 学号@mail.nankai.edu.cn.xxx.com xxx.com为自己的域名邮箱
> > 
> > * 从自己的域名邮箱拿到验证码
> > 
> > * reset/password接口传入 学号@mail.nankai.edu.cn   emailCaptcha传入.xxx.com+验证码，还是可以绕过
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 另外，md5函数的这种写法很容易受到 hash长度扩展攻击 ，推荐使用更安全的密码算法
> 
> 对验证码再 hash 了一次，不知道这种做法是不是密码学上的最佳实践。
> 
> 这里的 hash 方法改成了 blake2，但是落库的密码因为历史原因还是保留 md5，要改的话所有人都必须重置密码，代价有点大。
> 
> 虽然 md5 已经不安全了，不过我想了解一下对这个oj来说可以用合理的代价达成一次攻击吗？

感觉这次应该就没什么大问题了，其实我之前说的`hash长度扩展攻击`也只是针对验证码机制，对库中的密码影响不大
